server:
  port: 8082
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: laboratoryStudent
  datasource:
    url: jdbc:mysql://localhost:3306/laboratory?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: mapper/*.xml


